"""empty message

Revision ID: 4c03f663587e
Revises: c317278ecc80
Create Date: 2021-07-28 13:38:32.432475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c03f663587e'
down_revision = 'c317278ecc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('workout_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activities', 'workouts', ['workout_id'], ['id'])
    op.drop_constraint('workouts_activity_id_fkey', 'workouts', type_='foreignkey')
    op.drop_column('workouts', 'activity_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workouts', sa.Column('activity_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('workouts_activity_id_fkey', 'workouts', 'activities', ['activity_id'], ['id'])
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'workout_id')
    # ### end Alembic commands ###
