"""empty message

Revision ID: e464f27e636f
Revises: 4c03f663587e
Create Date: 2021-07-29 16:43:02.634070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e464f27e636f'
down_revision = '4c03f663587e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activities_exercise_id_fkey', 'activities', type_='foreignkey')
    op.drop_constraint('activities_workout_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'workouts', ['workout_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'activities', 'exercises', ['exercise_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_workout_id_fkey', 'activities', 'workouts', ['workout_id'], ['id'])
    op.create_foreign_key('activities_exercise_id_fkey', 'activities', 'exercises', ['exercise_id'], ['id'])
    # ### end Alembic commands ###
